spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/?user=root
    username: root
    password: 1339014436
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
